#!/usr/bin/env python3
"""The site's one switch: in season, or offseason.

site.json holds it:   {"mode": "season", "season": 2026}

Run this after changing it (publish.sh runs it every time). It rewrites the tab
bar on every page for the mode and regenerates index.html as a copy of the
mode's home page, so the root URL -- the one everyone has bookmarked -- always
shows what matters right now, and the other year's tools stay one tab away.

  season     Roster Tracker · Trades · On the Block · Past Rosters · Draft History · <year> Offseason
             The Offseason tab opens the keeper planner (keepers.html), with By Position,
             ESPN ADP, Price Moves, Budgets and Draft Pool as sub-tabs beneath it.
  offseason  Keepers · By Position · ESPN ADP · Price Moves · Trades · Budgets · Draft Pool ·
             On the Block · Past Rosters · Draft History · Roster Tracker

index.html is generated -- edit tracker.html or keepers.html, then run this.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE_URL = "https://mheinlen31.github.io/sunday-funday/"

LABEL = {
    "tracker.html": "Roster Tracker", "keepers.html": "Keepers", "positions.html": "By Position",
    "adp.html": "ESPN ADP", "moves.html": "Price Moves", "trades.html": "Trades",
    "budgets.html": "Budgets", "pool.html": "Draft Pool", "block.html": "On the Block",
    "rosters.html": "Past Rosters", "drafts.html": "Draft History",
}
OFFSEASON_TOOLS = ["keepers.html", "positions.html", "adp.html", "moves.html", "budgets.html", "pool.html"]
MODES = {
    "season": {
        "home": "tracker.html",
        "main": ["tracker.html", "trades.html", "block.html", "rosters.html", "drafts.html"],
        "group": OFFSEASON_TOOLS,                 # folded under one "<year> Offseason" tab
    },
    "offseason": {
        "home": "keepers.html",
        "main": ["keepers.html", "positions.html", "adp.html", "moves.html", "trades.html", "budgets.html",
                 "pool.html", "block.html", "rosters.html", "drafts.html", "tracker.html"],
        "group": None,
    },
}
NAV_RE = re.compile(r'<nav class="pagetabs">.*?</nav>(?:\s*<nav class="subtabs">.*?</nav>)?', re.S)


def tab(page, current, home):
    href = "./" if page == home else page
    return f'      <a href="{href}"{" class=\"active\"" if page == current else ""}>{LABEL[page]}</a>'


def nav_for(current, cfg, season):
    lines = ['<nav class="pagetabs">'] + [tab(p, current, cfg["home"]) for p in cfg["main"]]
    if cfg["group"]:
        active = ' class="active"' if current in cfg["group"] else ""
        lines.append(f'      <a href="{cfg["group"][0]}"{active}>{season} Offseason</a>')
    lines.append("    </nav>")
    if cfg["group"] and current in cfg["group"]:
        lines += ['    <nav class="subtabs">'] + [tab(p, current, cfg["home"]) for p in cfg["group"]] + ["    </nav>"]
    return "\n".join(lines)


def main():
    site = json.loads((ROOT / "site.json").read_text())
    mode, season = site["mode"], site["season"]
    if mode not in MODES:
        sys.exit(f"site.json mode must be one of {sorted(MODES)}, not {mode!r}")
    cfg = MODES[mode]
    changed = 0
    for page in LABEL:
        path = ROOT / page
        html = path.read_text()
        new, n = NAV_RE.subn(lambda m: nav_for(page, cfg, season), html, count=1)
        if n != 1:
            sys.exit(f"{page}: no tab bar found to rewrite")
        if new != html:
            path.write_text(new)
            changed += 1
    home = (ROOT / cfg["home"]).read_text()
    home = home.replace("<!DOCTYPE html>",
                        f"<!DOCTYPE html>\n<!-- GENERATED by scripts/site_mode.py from {cfg['home']} -- edit that file, then run the script -->", 1)
    home = home.replace(f'content="{SITE_URL}{cfg["home"]}"', f'content="{SITE_URL}"')
    index = ROOT / "index.html"
    if not index.exists() or index.read_text() != home:
        index.write_text(home)
        changed += 1
    print(f"mode {mode}: home page = {cfg['home']}; {changed} file(s) rewritten")


if __name__ == "__main__":
    main()
